version: '3.5'

services:
  openvpn:
    image: hwdsl2/ipsec-vpn-server
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    restart: always
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - VPN_IPSEC_PSK=blahblah
      - VPN_USER=sahputra
      - VPN_PASSWORD=password
    deploy:
      labels:
        - "traefik.backend=openvpn"
        - "traefik.frontend.rule=Host:openvpn.synker.ovh"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.enable=true"
        - "traefik.port=1194"
        - "traefik.docker.network=ntw_front"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.size == small
    networks:
      - ntw_front
networks:
  ntw_front:
    external: true