language: generic
addons:
  ssh_known_hosts:
  - $SERVER_IP
script:
  - ls
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh $USER@SERVER_IP chmod +x ~/synker-docker/runup.sh && ~/synker-docker/runup.sh
  on:
    branch: master