version: "3.4"

services:
  consul:
    image: consul:${CONSUL_VERSION:-1.4.4}
    command: agent -server -bootstrap-expect=1 -ui -disable-host-node-id
    volumes:
      - consul_data:/consul/data
    ports:
      - "8500:8500"
      - "53:53/udp"
      - "8300:8300"
      - "8301:8301"
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true, "disable_update_check":true}'
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_BIND_INTERFACE=eth0
    deploy:
      labels:
      - "traefik.backend=consul"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:consul.synker.ovh"
      - "traefik.docker.network=ntw_front"
      - "traefik.port=8500"
      - "traefik.enable=true"
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - ntw_front
      - monitoring

networks:
  monitoring:
    driver: overlay
    external: true
  ntw_front:
    driver: overlay
    external: true

volumes:
  consul_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=151.80.235.155"
      device: ":/mnt/nfs/consul/data"