version: "3.5"

services:

  system-prune:
    image: docker
    networks:
      - monitoring
      - ntw_front
      - ingress_net_backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: docker system prune --all --force
    deploy:
      mode: global
      restart_policy:
        delay: 24h

  backup_consul:
    image: jordancrawford/rpi-cold-storage-rsync
    networks:
      - monitoring
      - ntw_front
    volumes:
      - "/mnt/nfs/consul:/backupsource"
      - "/mnt/freebox/backup_synker/consul:/backupdest"
    # command: --exclude="config"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.labels.archi==armhf
      restart_policy:
        delay: 24h

  backup_postgres:
    image: jordancrawford/rpi-cold-storage-rsync
    networks:
      - monitoring
      - ntw_front
    volumes:
      - "/mnt/nfs/postgres/data:/backupsource"
      - "/mnt/freebox/backup_synker/postgres:/backupdest"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.labels.archi==armhf
      restart_policy:
        delay: 24h

networks:
  monitoring:
    external: true
  ingress_net_backend:
    external: true
  ntw_front:
    external: true