version: "3.4"

services:

  traefik_init:
    image: traefik:${TRAEFIK_VERSION:-1.6.5-alpine}
    command:
      - "traefik"
      - "storeconfig"
      # - "--api"
      - "--debug"
      - "--logLevel=INFO"
      - "--traefikLog.filePath=/log/traefik/log.json"
      - "--traefikLog.format=json"
      - "--web"
      - "--web.address=:8080"
      - "--web.readonly"
      - "--web.statistics"
      - "--checknewversion=true"
      - "--insecureskipverify=true"
     # - "--entrypoints=Name:http Address::80 ProxyProtocol:true Compress:true Redirect.EntryPoint:https"
      # - "--entrypoints=Name:http Address::80 ProxyProtocol:true Compress:true Auth.Basic.Users:admin:$$apr1$$8Dlf//P1$$aE5beYa7YLUDWZ16D9F6b1"
      # - "--entrypoints=Name:https Address::443 TLS Compress:true ProxyProtocol:true Auth.Basic.Users:admin:$$apr1$$8Dlf//P1$$aE5beYa7YLUDWZ16D9F6b1"
      - "--entrypoints=Name:http Address::80 ProxyProtocol:true Compress:true"
      - "--entrypoints=Name:https Address::443 TLS Compress:true ProxyProtocol:true"
      - "--defaultentrypoints=http,https"
      - "--acme"
      # - "--acme.domains=synker.ovh,api.synker.ovh,visu.synker.ovh,kibana.synker.ovh,elastic.synker.ovh,rabbitmq.synker.ovh,consul.synker.ovh,adminer.synker.ovh,media.synker.ovh"
      - "--acme.domains=synker.ovh,*.synker.ovh"
      - "--acme.storage=etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.dnschallenge"
      - "--acme.dnsChallenge.provider=ovh"
      - "--acme.dnsChallenge.delayBeforeCheck=0"
      - "--acme.acmelogging=true"
      - "--acme.OnHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=support@synker.ovh"
      #- "--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=docker.localhost"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--consul"
      - "--consul.endpoint=consul.synker.ovh:8500"
      - "--consul.prefix=traefik"
      #- --consulcatalog=true
      #- --consulcatalog.endpoint=consul.synker.ovh:8500
      # - --consulcatalog.constraints="tag==public
    networks:
      - ntw_front
    environment:
      - OVH_ENDPOINT=ovh-eu
      - OVH_APPLICATION_KEY=jEncYct1dwXs3Muq
      - OVH_APPLICATION_SECRET=MvW4JHaARs5IoLxvajIQ6L2cMkh7gqgm
      - OVH_CONSUMER_KEY=Apyv5abNEVToRsrLM54sKrqN1IRRwRpJ
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s

networks:
  ntw_front:
    driver: overlay
    external: true
