version: "3.5"

services:
  nginx-proxy:
    image: nginx:${NGINX_VERSION:-1.15-alpine}
    networks:
      - ntw_front
    ports:
      - "88:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
      - "traefik.tags=proxy"
      - "traefik.backend=nginx-proxy"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:media.synker.ovh"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.docker.network=ntw_front"
      - "traefik.port=88"
      - "traefik.enable=true"
    volumes:
      - nginx_html:/usr/share/nginx/html
      - nginx_log:/var/log/nginx
volumes:
  nginx_html:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=151.80.235.155"
      device: ":/mnt/nfs/nginx-proxy/html"
  nginx_log:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=151.80.235.155"
      device: ":/mnt/nfs/nginx-proxy/log"
 
networks:
  ntw_front:
    external: true

configs:
  nginx_config:
    file: ./nginx-proxy/default.conf