version: "3.5"

services:
  nginx-proxy-letsencrypt:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
    deploy:
      mode: replicated
      replicas: 1

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/default.conf:/etc/nginx/nginx.conf:ro
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5m
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.size == large
      labels:
         com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

volumes:
  nginx_certs:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=151.80.235.155"
      device: ":/mnt/nfs/media/certs"
  nginx_html:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=151.80.235.155"
      device: ":/mnt/nfs/media/html"
 
networks:
  ntw_front:
    external: true