version: "3.5"

services:
   homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:latest
    volumes:
      - homeassistant_config:/config
    networks:
      - ntw_front
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Paris
      - PASSWORD=passwd
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 180s
        order: start-first
      placement:
        constraints:
          - node.labels.hostname == rasp1
          - node.role==worker
      labels:
      - "traefik.tags=homeassistant"
      - "traefik.backend=homeassistant"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:domotic.synker.ovh"
      - "traefik.docker.network=ntw_front"
      - "traefik.http.port=8123"
      - "traefik.enable=true"
volumes:
  homeassistant_config:
     driver_opts:
      type: "nfs"
      o: "addr=151.80.235.155,nolock,soft,rw"
      device: ":/mnt/nfs/domotic/config"
  
networks:
  ntw_front:
    external: true
