version: "3.5"

services:
  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 'jeedom'
      MYSQL_USER: 'jeedom'
      MYSQL_PASS: 'jeedom'
      TZ: 'Europe/Paris'
    volumes:
      - domotic_db_data:/var/lib/mysql
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 180s
        order: start-first
      placement:
        constraints:
          - node.role==worker
      labels:
      - "traefik.tags=domotic"

  jeedom:
    image: jeedom/jeedom:stable
    volumes:
      - jeedom_data:/var/www/html
    environment:
      ROOT_PASSWORD: 'jeedom'
    ports:
      - "9022:22"
      - "9080:80"
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 180s
        order: start-first
      placement:
        constraints:
          - node.labels.hostname==rasp1
          - node.role==worker
      labels:
      - "traefik.tags=domotic"
      - "traefik.backend=jeedom"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:domotic.synker.ovh"
      - "traefik.docker.network=ntw_front"
      - "traefik.port=9080"
      - "traefik.enable=true"
    depends_on:
      - mysql

volumes:
  jeedom_data:
     driver_opts:
      type: "nfs"
      o: "addr=151.80.235.155,nolock,soft,rw"
      device: ":/mnt/nfs/domotic/data"
  domotic_db_data:
     driver_opts:
      type: "nfs"
      o: "addr=151.80.235.155,nolock,soft,rw"
      device: ":/mnt/nfs/domotic/db/data"
networks:
  ntw_front:
    external: true
