version: "3.3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:${TAG:-6.2}
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.zen.minimum_master_nodes=1
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - node.name=elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ingress_net_backend
    ports:
      - ${ELASTICSEARCH_PORT:-9200}:9200
    deploy:
      labels:
        - "traefik.backend=elasticsearch"
        - "traefik.frontend.rule=Host:elastic.synker.ovh"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=9200"
        - "traefik.enable=true"
        - "traefik.docker.network=ingress_net_backend"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20m
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.size == large

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG:-6.2}
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    networks:
      - ingress_net_backend
    deploy:
      labels:
       - "traefik.backend=kibana"
       - "traefik.frontend.rule=Host:kibana.synker.ovh"
       - "traefik.frontend.entryPoints=http,https"
       - "traefik.backend.loadbalancer.swarm=true"
       - "traefik.backend.loadbalancer.method=drr"
       - "traefik.enable=true"
       - "traefik.port=5601"
       - "traefik.docker.network=ingress_net_backend"
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == medium
    # healthcheck:
    #   test: wget -qO- http://kibana:5601 > /dev/null
    #   interval: 20m
    #   retries: 3
    volumes:
      - kibana_data:/usr/share/kibana/data

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG:-6.2}
    # configs: # https://docs.docker.com/compose/compose-file/#long-syntax
    #   - source: ls_config
    #     target: /usr/share/logstash/config/logstash.yml
    #     mode: 0440
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    #   - 'xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}'
    #   - 'xpack.monitoring.elasticsearch.username=${ELASTICSEARCH_USERNAME}'
    #   - 'xpack.monitoring.elasticsearch.url="http://elasticsearch:9200"'
    #   - 'path.config="/usr/share/logstash/config"'
    ports:
      - "12201:12201/udp"
      - "9600:9600"
      - "5045:5045"
    networks:
      - ingress_net_backend
    volumes:
      - logstash_config:/usr/share/logstash/config
      - logstash_pipeline:/usr/share/logstash/pipeline
      - logstash_data:/var/lib/logstash
      - logstash_log:/var/log/logstash
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3m
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.provider == ovh
    depends_on: 
        - elasticsearch

volumes:
  elasticsearch_data:
     driver_opts:
      type: "nfs"
      #o: "rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,nolock,soft,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,local_lock=none,no_root_squash,addr=35.156.117.97"
      o: "nolock,soft,rw,addr=35.156.117.97"
      device: ":/webgrab_volume/elastic/data"
  kibana_data:
     driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=35.156.117.97"
      device: ":/webgrab_volume/kibana/data"
  
  logstash_config:
    driver_opts:
      type: "nfs"
      o: "addr=35.156.117.97,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/config"
  logstash_pipeline:
    driver_opts:
      type: "nfs"
      o: "addr=35.156.117.97,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/pipeline"
  logstash_data:
    driver_opts:
      type: "nfs"
      o: "addr=35.156.117.97,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/data"
  logstash_log:
    driver_opts:
      type: "nfs"
      o: "addr=35.156.117.97,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/log"

configs:
  ls_config:
    file: $PWD/logstash/config/logstash.yml

networks:
  ingress_net_backend:
    external: true