version: '3'

services:

  synker_db:
    image: mariadb:${MYSQL_VERSION}
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/MYSQL_PASSWORD
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8889:3306"
    networks:
      - elk_elk
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql_password
      - mysql_root_password
     deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20m
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.size == large
volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/mariadb/data"
secrets:
  mysql_password:
    external: true
  mysql_root_password:
    external: true
networks:
  elk_elk:
    external: true