version: '3.5'

services:

  synker_db:
    image: mariadb:${MYSQL_VERSION}
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: /run/secrets/mysql_password
      MYSQL_DATABASE: playlist
      MYSQL_ROOT_HOST: "%"
    ports:
      - "8889:3306"
    networks:
      - elk_elk
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
     mode: replicated
     replicas: 1
     restart_policy:
       condition: on-failure
       delay: 20m
       max_attempts: 3
       window: 120s
     placement:
       constraints: 
         - node.labels.size == large
    secrets:
      - "mysql_password"
      - "mysql_root_password"
volumes:
  mariadb_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/mariadb/data"
secrets:
  mysql_password:
    file: MYSQL_PASSWORD.txt
  mysql_root_password:
    file: MYSQL_ROOT_PASSWORD.txt
networks:
  elk_elk:
    external: true