version: "3.3"
services:
  rabbit1:
    image: rabbitmq:${RABBIT_TAG}-management-alpine
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "8000:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    networks:
      - elk_elk

  rabbit2:
    image: rabbitmq:${RABBIT_TAG}-management-alpine
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "8001:15672"
    networks:
      - elk_elk
    depend_on:
      - rabbit1

networks:
  elk_elk:
    external: true