version: "3.3"
services:
  rabbit1:
    image: rabbitmq:3.6.9-management-alpine
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "8000:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=mycookie
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - elk_elk

  rabbit2:
    image: rabbitmq:3.6.9-management-alpine
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=mycookie
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "8001:15672"
    networks:
      - elk_elk

  rabbit3:
    image: rabbitmq:3.6.9-management-alpine
    hostname: rabbit3
    environment:
      - RABBITMQ_ERLANG_COOKIE=mycookie
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
    ports:
      - "5674:5672"
      - "8002:15672"
    networks:
      - elk_elk
networks:
  elk_elk:
    external: true