version: "3.3"
services:
  rmq:
    image: lovelysystems/rabbitmq-swarm-cluster
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - RABBITMQ_ERLANG_COOKIE=abc
      - RABBITMQ_USE_LONGNAME=true
      #- RABBITMQ_MNESIA_DIR=/var/lib/rabbitmq/mnesia
      - RABBITMQ_PLUGINS_EXPAND_DIR=/var/lib/rabbitmq/mnesia/plugins-expand
      - SERVICE_NAME={{.Service.Name}}
      - SLOT={{.Task.Slot}}
      - MASTER_SLOT=1
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672"   # amqp
      - "15672:15672" # web ui
volumes:
  rabbit_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/rabbitmq/data"
networks:
  elk_elk:
    external: true