version: "3.4"

services:
  consul:
    image: consul:${CONSUL_VERSION:-latest}
    hostname: consul
    command: agent -server -bootstrap-expect=1 -data-dir=/consul/data -ui -client=0.0.0.0 -disable-host-node-id -domain=consul.synker.ovh
    ports:
      - "8500:8500"
      - "8300:8300"
    volumes:
      - consul_data:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true, "disable_update_check": true}'
      #- CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_BIND_INTERFACE=eth0
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    deploy:
      labels:
      - "traefik.backend=consul"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:consul.synker.ovh"
      - "traefik.docker.network=ntw_front"
      - "traefik.port=8500"
      - "traefik.enable=true"
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - ntw_front

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    depends_on:
      - consul
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - ntw_front
      - ingress_net_backend
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --consul --consul.endpoint=consul:8500
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
 
  visu:
    image: dockersamples/visualizer:stable
    stop_grace_period: 1m30s
    depends_on:
      - traefik
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      labels:
      - "traefik.backend=visu"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:visu.synker.ovh"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=ingress_net_backend"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.role == manager
          - node.labels.size == small
    networks:
      - ingress_net_backend

networks:
  ingress_net_backend:
    external: true
  ntw_front:
    external: true

volumes:
  consul_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=35.156.117.97"
      device: ":/webgrab_volume/consul/data"
configs:
  traefik.toml:
    file: ./configs/traefik.toml