version: "3.4"

services:

  traefik:
    image: traefik:1.5
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    networks:
      - ntw_front
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --docker \
      --docker.swarmmode \
      --docker.domain=synker.ovh \
      --docker.watch \
      --debug=true \
      --logLevel=WARN \
      --web \
      --web.address=:8080
    deploy:
      mode: global
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      labels:
      - "traefik.backend=lb_visualizer"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:visu.synker.ovh"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=ntw_front"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.role == manager
          - node.labels.size == small
    networks:
      - ntw_front

  consul:
    image: consul
    command: agent -server -bootstrap-expect=1 -ui -bootstrap -log-level warn -client 0.0.0.0
    volumes:
      - consul_data:/consul/data
    ports:
      - "8500:8500"
      - "8400:8400"
      - "53:8600/udp"
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true, "disable_update_check": true}'
      - CONSUL_BIND_INTERFACE=eth0
    deploy:
      replicas: 1
      labels:
      - "traefik.backend=lb_consul"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:consul.synker.ovh"
      - "traefik.docker.network=ntw_front"
      - "traefik.backend.loadbalancer.swarm=true"
      - "traefik.backend.loadbalancer.method=drr"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - ntw_front

  who2:
    image: emilevauge/whoami
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.20'
          memory: 9M
        reservations:
          cpus: '0.05'
          memory: 9M
      labels:
      - traefik.backend=who2
      - "traefik.frontend.rule=PathPrefixStrip:/who2"
      - traefik.port=80
      - traefik.weight=10
      - traefik.enable=true
      - traefik.passHostHeader=true
      - traefik.docker.network=ntw_front
      - traefik.frontend.entryPoints=http
      - traefik.backend.loadbalancer.swarm=true
      - traefik.backend.loadbalancer.method=drr

networks:
  elk_elk:
    external: true
  ntw_front:
    external: true

volumes:
  consul_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=35.156.117.97"
      device: ":/webgrab_volume/consul/data"
configs:
  traefik.toml:
    file: ./configs/traefik.toml