version: "3.4"
services:
  traefik_init:
    image: traefik:1.5
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.OnHostRule=true"
      - "--acme.onDemand=true"
      - "--acme.dnsProvider=ovh"
      - "--acme.email=support@synker.ovh"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=www.synker.ovh"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - consul

  traefik:
    image: traefik:1.5
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk_elk
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8089:8080"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  consul:
    image: consul
    hostname: consul
    command: agent -server -bootstrap-expect=1 -ui -bootstrap -log-level warn
    volumes:
      - consul_data:/consul/data
    
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8400:8400"
      - "8600:53/udp"
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true, "disable_update_check": true}'
      - CONSUL_BIND_INTERFACE=eth0
    deploy:
      labels:
        - "traefik.backend=consul"
        - "traefik.frontend.rule=Host:consul.synker.ovh"
        - "traefik.enable=true"
        - "traefik.port=8500"
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik

networks:
  elk_elk:
    external: true
  traefik:
    driver: host

volumes:
  consul_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/consul/data"