version: "3.4"
services:
  traefik_init:
    image: traefik:v1.5.3
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.domain=synker.ovh"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - consul

  traefik:
    image: traefik:v1.5.3
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk_elk
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8089:8080"
    deploy:
      mode: global
      labels:
        - "traefik.port=8089"
        - "traefik.backend=traefik"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:traefik.synker.ovh"
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  consul:
    image: consul
    hostname: consul
    command: agent -server -bootstrap-expect=1 -ui -bootstrap -log-level warn -client 0.0.0.0
    volumes:
      - consul_data:/consul/data
    ports:
      - "8500:8500"
      - "8400:8400"
      - "53:8600/udp"
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true, "disable_update_check": true}'
      - CONSUL_BIND_INTERFACE=eth0
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8500"
        - "traefik.backend=consul"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:consul.synker.ovh"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik

networks:
  elk_elk:
    external: true
  traefik:
    driver: overlay

volumes:
  consul_data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=35.156.117.97"
      device: ":/webgrab_volume/consul/data"