global:
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'alertmanager@gmail.com'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '%smtp_auth_password_secret%'
  # smtp_require_tls: false
  # smtp_hello: 'alert.synker.ovh'
  slack_api_url: '%slack_am%'
# The root route on which each incoming alert enters.
route:
  receiver: slack_general
  group_by: [ alertname, service, cluster]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  routes:
  - receiver: 'slack_general'
    match_re:
      service: synker|elasticsearch
  - receiver: 'perso_outlook_email'
    match:
      severity: warning
  - receiver: 'pushover'
    match:
      severity: warning

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'service']

receivers:
- name: 'perso_gmail_email'
  email_configs:
  - to: 'heni.fazzani@gmail.com'

- name: 'perso_outlook_email'
  email_configs:
  - to: 'fazzani.heni@outlook.fr'

- name: slack_general
  slack_configs:
  - send_resolved: true
    username: 'monitoring'
    channel: '#general'
    api_url: '%slack_hook_secret%'

- name: pushover
  pushover_configs:
  - send_resolved: true
    user_key: '%PUSHHOVER_USER_KEY%'
    token: '%PUSH_HOVER_API_TOKEN%'