{
 "title": "Containers",
 "description": "Container metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Node", "query": "netdata_info" }
  ]
 },
 "panels": [
  {
   "title": "Container Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_stack_namespace=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\" ) ) by (node_id) * on (node_id) group_left(state) swarm_node_info{instance=~\"($node_id):9323\"})"
    }
   ]
  },
  {
   "title": "Docker Stacks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_stack_namespace=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\" ) * on (node_id) group_left(state) swarm_node_info{job=~\"dockerd-($node_id)\"}) by (container_label_com_docker_stack_namespace) )"
    }
   ]
  },
  {
   "title": "Docker Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_swarm_service_name=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\") * on(node_id) group_left(state) swarm_node_info{job=~\"dockerd-($node_id)\"}) by (container_label_com_docker_swarm_service_id))"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(netdata_cgroup_cpu_percentage_average{instance=~\"($node_id)\"}) by (chart,instance))"
    }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_health_checks_failed_total{job=~\"dockerd-($node_id)\"}[5m]) ) )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top CPU Usage by Docker Service",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!~\"\",instance=~\"($node_id)\"}[1m])) by (container_label_com_docker_swarm_service_name) ) > 0.1",
     "legendFormat": "CPU: {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Node Failed Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_health_checks_failed_total{job=~\"dockerd-($node_id)\"}[5m]) ) ) by (job)",
     "legendFormat": "{{job}} failed"
    }
   ]
  },
  {
   "title": "Top Memory Usage by Docker Service",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name!~\"\",instance=~\"($node_id)\"}) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Top CPU Usage by Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(label_replace(netdata_cgroup_cpu_percentage_average{instance=~\"($node_id)\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_)(.*).cpu\") ) by (chart,instance) ) > 0.1",
     "legendFormat": "{{instance}} {{chart}}"
    }
   ]
  },
  {
   "title": "Container Node Disk Read IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_io_KiB_persec_average{family=~\"/var.*\",dimension=\"reads\",instance=~\"($node_id)\"} ) by (instance) > 0",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Read FS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, rate(container_fs_reads_bytes_total{instance=~\"($node_id)\"}[1m])) > 0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Container Node Disk Write IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "- sum(netdata_disk_io_KiB_persec_average{family=~\"/pxd.*|/var.*\",dimension=\"writes\",instance=~\"($node_id)\"} ) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Write FS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, rate(container_fs_writes_bytes_total{instance=~\"($node_id)\"}[1m]) ) > 0",
     "legendFormat": "{{instance}} {{id}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"}) by (instance) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Memory Usage by Container",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(label_replace(netdata_cgroup_mem_MiB_average{instance=~\"($node_id)\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_)(.*).mem\") ) by (chart,instance) )",
     "legendFormat": " {{instance}} {{chart}}"
    }
   ]
  },
  {
   "title": "Node Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{chart=~\"cgroup_.*\", dimension=\"received\",instance=~\"($node_id)\"}) by (instance) > 0",
     "legendFormat": "IN: {{instance}}"
    },
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{chart=~\"cgroup_.*\", dimension=\"sent\",instance=~\"($node_id)\"}) by (instance) < 0",
     "legendFormat": "OUT: {{instance}}"
    }
   ]
  },
  {
   "title": "Top Network Usage by Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, rate(container_network_receive_bytes_total{id!~\"/\",instance=~\"($node_id)\"}[1m]) * 8 > 0 )",
     "legendFormat": "IN: {{instance}} {{task}}"
    },
    {
     "expr": "- topk(1, rate(container_network_transmit_bytes_total{id!~\"/\",instance=~\"($node_id)\"}[1m]) * 8 > 0 )",
     "legendFormat": "OUT: {{instance}} {{task}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_container_actions_seconds_count[5m]) ) ) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Node LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"net et|net.et.*|net en.*|net.en*\",dimension=\"received\",instance=~\"($node_id)\"}) by (instance)> 50",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"net et|net.et.*|net en.*|net.en*\",dimension=\"sent\",instance=~\"($node_id)\"}) by (instance) < 50",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Top Network Usage by Docker Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name!~\"\",instance=~\"($node_id)\"}[1m]) * 8 > 20000 ) by (container_label_com_docker_swarm_service_name,instance)) ",
     "legendFormat": "IN: {{instance}} {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "- topk(1, sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name!~\"\",instance=~\"($node_id)\"}[1m]) * 8 > 20000 ) by (container_label_com_docker_swarm_service_name,instance))",
     "legendFormat": "OUT: {{instance}} {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Docker Network Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_network_actions_seconds_count[5m]) ) ) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Container Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(label_replace(engine_daemon_engine_info{instance=~\"($node_id):9323\"},\"instance\",\"$1\",\"instance\",\"(.*):9323\")  ) by (instance, kernel, os, version)"
    },
    {
     "expr": "count(sum(netdata_cgroup_cpu_percentage_average{instance=~\"($node_id)\"}) by (instance,chart)) by (instance)"
    },
    {
     "expr": "label_replace(swarm_node_manager{instance=~\"($node_id):9323\"}, \"instance\", \"$1\", \"instance\", \"(.*):9323\")"
    },
    {
     "expr": "sum(netdata_cgroup_cpu_percentage_average{instance=~\"($node_id)\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Running Docker and OCI Containers",
   "type": "table",
   "gridPos": { "h": 50, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "container_tasks_state{id!~\"/|/docker|/system.slice.*|/user.slice.*\", instance=~\"($node_id)\" ,state=\"running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}