{
 "title": "Nodes",
 "description": "Cluster node metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Node", "query": "netdata_info" }
  ]
 },
 "panels": [
  {
   "title": "Lowest Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, netdata_system_uptime_seconds_average{instance=~\"($node_id)\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(netdata_info{instance=~\"($node_id)\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MiB_average{instance=~\"($node_id)\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(netdata_cgroup_writeback_MiB_average{instance=~\"($node_id)\"})"
    }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_health_checks_failed_total{job=~\"dockerd-($node_id)\"}[5m]) ) )"
    }
   ]
  },
  {
   "title": "Cluster LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"received\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"sent\"})",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Node Free /",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_disk_space_GiB_average{family=\"/\",dimension=~\"avail\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Free /var/lib/docker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_disk_space_GiB_average{family=\"/var/lib/docker\",dimension=~\"avail\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Read Operations",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(netdata_disk_ops_operations_persec_average{family!=\"/etc/resolv.conf\",dimension=\"reads\"}))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Container Storage Read FS",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=~\"($node_id)\"}[1m])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Write Operations",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- sum(netdata_disk_ops_operations_persec_average{family!=\"/etc/resolv.conf\",dimension=\"writes\"})",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Container Storage Write FS",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=~\"($node_id)\"}[1m]) ) by (instance)",
     "legendFormat": "{{instance}} {{id}}"
    }
   ]
  },
  {
   "title": "Node Load Factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{dimension=\"load1\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Banned IPs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(netdata_jail_in_jail_IPs_average)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest CPU Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"}) by (instance) )"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, sum(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\".*\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_system_ram_MiB_average{instance=~\"($node_id)\"} ) by (instance) * sum(netdata_system_ram_MiB_average{dimension=~\"free|cached\",instance=~\"($node_id)\"} ) by (instance) ) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_system_ram_MiB_average{instance=~\"($node_id)\"}) by (instance) * sum(netdata_system_ram_MiB_average{dimension=~\"free|cached\",instance=~\"($node_id)\"}) by (instance) ) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Free /",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_disk_space_GiB_average{family=\"/\", instance=~\"($node_id)\"}) by (instance) * sum(netdata_disk_space_GiB_average{family=\"/\",dimension=~\"avail|cached\",instance=~\"($node_id)\"} ) by (instance) ) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, 100 / sum(netdata_disk_space_GiB_average{family=\"/\", instance=~\"($node_id)\"}) by (instance) * sum(netdata_disk_space_GiB_average{family=\"/\",dimension=~\"avail|cached\",instance=~\"($node_id)\"} ) by (instance) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"}) by (instance) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Read Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(netdata_disk_ops_operations_persec_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance)) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (Cached)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{dimension=\"cached\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Write Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- ceil(sum(netdata_disk_ops_operations_persec_average{family!=\"/etc/resolv.conf\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance) ) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (Used)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{dimension=\"used\",instance=~\"($node_id)\"}",
     "legendFormat": "Memory: {{instance}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(netdata_cgroup_cpu_percentage_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU IO Wait",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_cpu_cpu_percentage_average{dimension=\"iowait\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_cgroup_mem_MiB_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{chart=~\"cgroup_.*\", dimension=\"received\"}) by (instance) > 0",
     "legendFormat": "IN: {{instance}}"
    },
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{chart=~\"cgroup_.*\", dimension=\"sent\"}) by (instance) < 0",
     "legendFormat": "OUT: {{instance}}"
    }
   ]
  },
  {
   "title": "Node LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 28 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"received\",instance=~\"($node_id)\"} > 0",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"sent\",instance=~\"($node_id)\"} < 0",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_files_open_files_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_files_open_files_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Node Disk Read IO",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_io_KiB_persec_average{family=~\"/var.*\",dimension=\"reads\",instance=~\"($node_id)\"} ) by (instance) > 0",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Container Node Disk Read Operations",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(netdata_disk_ops_operations_persec_average{family=~\"/var.*|/pxd.*\",dimension=\"read\",instance=~\"($node_id)\"}) by (instance) ) > 0",
     "legendFormat": "Reads {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Read IO",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 33 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_io_KiB_persec_average{family!=\"/etc/resolv.conf\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Pipes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_groups_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_apps_pipes_open_pipes_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_pipes_open_pipes_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_groups_pipes_open_pipes_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Node Disk Write IO",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "- sum(netdata_disk_io_KiB_persec_average{family=~\"/pxd.*|/var.*\",dimension=\"writes\",instance=~\"($node_id)\"} ) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Node Disk Write Operations",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- ceil(sum(netdata_disk_ops_operations_persec_average{family=~\"/var.*\",dimension=\"writes\",instance=~\"($node_id)\"} ) by (instance) ) > 0",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Write IO",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 36 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "- sum(netdata_disk_io_KiB_persec_average{family!=\"/etc/resolv.conf\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(count(netdata_cgroup_writeback_MiB_average{instance=~\"$node_id\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Read Wait per Operation",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_await_milliseconds_operation_average{family!=\"/etc/resolv.conf\",dimension=\"reads\",instance=~\"($node_id)\"} > 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_groups_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Write Wait per Operation",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "- sum(netdata_disk_await_milliseconds_operation_average{family!=\"/etc/resolv.conf\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_container_actions_seconds_count[5m]) ) ) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Docker Network Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_network_actions_seconds_count[5m]) ) ) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(label_replace(engine_daemon_engine_info{instance=~\"($node_id):9323\"},\"instance\",\"$1\",\"instance\",\"(.*):9323\")  ) by (instance, kernel, os, version)"
    },
    {
     "expr": "count(sum(netdata_cgroup_cpu_percentage_average{job=~\"netdata-($node_id)\"}) by (instance,chart)) by (instance)"
    },
    {
     "expr": "label_replace(swarm_node_manager{instance=~\"($node_id):9323\"}, \"instance\", \"$1\", \"instance\", \"(.*):9323\")"
    }
   ]
  }
 ]
}