global:
  evaluation_interval: 15s
  scrape_interval: 15s
  
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'swarm_task.rules'
  - 'swarm_node.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: cadvisor
    metrics_path: /metrics
    scrape_interval: 30s
    dns_sd_configs:
    - names:
        - "tasks.cadvisor"
      type: 'A'
      port: 8080
  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100