accessLogsFile = "/dev/stdout"
defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "synker.ovh"
watch = true
swarmmode = true
exposedbydefault = false

# Let’s Encrypt configuration
[acme]
email = "supprt@synker.ovh"
storageFile = "acme.json"
entryPoint = "https"
caServer = "https://acme-staging.api.letsencrypt.org/directory" # Staging Environment
# onHostRule = true
[acme.httpChallenge]
    entryPoint = "http"
[[acme.domains]]
  main = "synker.ovh"
  sans = ["consul.synker.ovh","viz.synker.ovh"]