accessLogsFile = "/dev/stdout"
InsecureSkipVerify = true
debug = true
checkNewVersion = true
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    #[entryPoints.http.redirect]
    #entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[web]
  address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "synker.ovh"
watch = true
swarmmode = true
exposedbydefault = false

# Let’s Encrypt configuration
[acme]
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"
email = "support@synker.ovh"
caServer = "https://acme-staging.api.letsencrypt.org/directory" # Staging Environment
storageFile = "acme.json"
# onHostRule = true

[[acme.domains]]
  main = "synker.ovh"
  sans = ["consul.synker.ovh","viz.synker.ovh"]