apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Elastic
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  orgId: 1
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true
  
- name: Elastic
  type: elasticsearch
  orgId: 1
  access: proxy
  database: "[metrics-]YYYY.MM.DD"
  url: https://elastic.synker.ovh
  jsonData:
    interval: Daily
    timeField: "@timestamp"