apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
  - name: Elastic

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true

- name: Elastic
  type: elasticsearch
  access: proxy
  database: "[metrics-]YYYY.MM.DD"
  url: https://elastic.synker.ovh
  jsonData:
    interval: Daily
    timeField: "@timestamp"