notifiers:
  - name: notif_slack_errors
    type: slack
    uid: notifier_slack_errors
    org_id: 1
    is_default: true
    send_reminders: true
    frequency: 1h
    disable_resolve_message: false
    # See `Supported Settings` section for settings supporter for each
    # alert notification type.
    settings:
      recipient: "Infra"
      uploadImage: true
      url: %slack_hook_secret%

  - name: notif_pushover
    type: pushover
    org_id: 1
    uid: pushhover1
    settings:
      apiToken: %PUSH_HOVER_API_TOKEN%
      userKey: %PUSHHOVER_USER_KEY%

  - name: email
    type: email
    org_id: 1
    # org_name: Synker
    uid: email1
    settings:
      addresses: heni.fazzani@gmail.com;fazzani.heni@outlook.fr


